export const projectData = [
    // Plugins
    {
        image: "/plugins/viewTwizzlay.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Twizzlay",
        description: "Ping Pong Delay Audio Plug-in",
        link: "https://earcandytech.com/twizzlay",
        github: "none",
    },
    {
        image: "/plugins/viewGummy.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Gummy Groove",
        description: "Chorus Audio Plug-in",
        link: "https://earcandytech.com/gummygroove",
        github: "none",
    },
    {
        image: "/plugins/viewSweetpoint.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "SweetPoint",
        description: "Smart Stereo Field Optimizer",
        link: "https://earcandytech.com/sweetpoint",
        github: "none",
    },
    {
        image: "/plugins/viewPhono.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Phonograin",
        description: "Granular Multi FX Audio Plug-in",
        link: "https://earcandytech.com/phonograin",
        github: "none",
    },
    {
        image: "/plugins/viewShape.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Shape",
        description: "Spectral Harmoniser Auditory Perceptual Enhancer",
        link: "https://www.oikla.com/",
        github: "none",
    },
    {
        image: "/plugins/viewTlaloc.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Tlaloc",
        description: "Granular Sampler",
        link: "none",
        github: "none",
    },
    {
        image: "/plugins/viewEsme.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Esmeralda",
        description: "Binaural Convolution Reverb",
        link: "https://earcandytech.com/esmeralda",
        github: "none",
    },
    {
        image: "/plugins/viewRuby.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Ruby",
        description: "Delay with Pitch Shifting",
        link: "https://earcandytech.com/ruby",
        github: "none",
    },
    {
        image: "/plugins/viewZafiro.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Zafiro",
        description: "Distortion with LFO modulation",
        link: "https://earcandytech.com/zafiro",
        github: "none",
    },
    {
        image: "/plugins/viewSpatial.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Spatializer",
        description: "Move audio through 2,4 and 8 speakers",
        link: "none",
        github: "none",
    },
    {
        image: "/plugins/viewFunnyDistor.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Funny Distortion",
        description: "Distortion",
        link: "none",
        github: "none",
    },
    {
        image: "/plugins/viewBanana.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Banana Split",
        description: "FM Synthesiser",
        link: "https://github.com/jsvaldezv/banana-split/releases",
        github: "https://github.com/jsvaldezv/banana-split",
    },
    // C++
    {
        image: "",
        category: "C++",
        technology: "C++",
        name: "Tetris",
        description: "Recreation of tetris game",
        link: "none",
        github: "none",
    },
    {
        image: "",
        category: "C++",
        technology: "C++",
        name: "Pong Game",
        description: "Recreation of pong game",
        link: "none",
        github: "none",
    },
    // Web development
    {
        image: "/webdev/viewECT.png",
        category: "Web Development",
        technology: "React JS and Firebase",
        name: "Ear Candy Technologies Website",
        description: "Current Company Website",
        link: "https://earcandytech.com/",
        github: "none",
    },
    {
        image: "/webdev/viewDrum.png",
        category: "Web Development",
        technology: "JavaScript",
        name: "Drum Machine",
        description: "Real Time Drum Machine in the Browser",
        link: "https://jsvaldezv.github.io/drum-machine/",
        github: "https://github.com/jsvaldezv/drum-machine",
    },
    {
        image: "/webdev/viewVisualsP5.png",
        category: "Web Development",
        technology: "JavaScript and p5",
        name: "Visuals p5",
        description: "Collection of audio visuals made in p5",
        link: "https://jsvaldezv.github.io/visuals-p5/",
        github: "https://github.com/jsvaldezv/visuals-p5",
    },
    {
        image: "/webdev/viewLiminal.png",
        category: "Web Development",
        technology: "React JS and Three js",
        name: "Liminal Spaces",
        description: "Virtual space inspired by La llorona",
        link: "https://jsvaldezv.github.io/liminal-spaces/",
        github: "https://github.com/jsvaldezv/liminal-spaces",
    },
    {
        image: "/webdev/viewSynthKids.png",
        category: "Web Development",
        technology: "JavaScript and Web Audio API",
        name: "Synth Kids",
        description: "Synth so children can learn music theory",
        link: "https://jsvaldezv.github.io/synth-kids/",
        github: "https://github.com/jsvaldezv/synth-kids",
    },
    {
        image: "/webdev/viewPluginsStore.png",
        category: "Web Development",
        technology: "React JS",
        name: "Audio Plug-ins Store",
        description: "Plug-in store as a web application",
        link: "none",
        github: "https://github.com/jsvaldezv/audio-plugins-store",
    },
    {
        image: "/webdev/viewMatrix.png",
        category: "Web Development",
        technology: "JavaScript",
        name: "Matrix Clock",
        description: "Digital and analog clock with matrix style",
        link: "https://jsvaldezv.github.io/matrix-clock/",
        github: "https://github.com/jsvaldezv/matrix-clock",
    },
    // Machine learning
    {
        image: "/py-ml/viewClass.png",
        category: "Python and ML",
        technology: "Python and Scikit Learn",
        name: "Instruments Classifier",
        description: "Trained with random forest",
        link: "none",
        github: "https://github.com/jsvaldezv/instruments-classifier",
    },
    {
        image: "/py-ml/viewArp.png",
        category: "Python and ML",
        technology: "Python",
        name: "MIDI Arpeggiator",
        description: "Arpeggiator based on Ableton's Live arp",
        link: "none",
        github: "https://github.com/jsvaldezv/midi-arpeggiator",
    },
    {
        image: "",
        category: "Python and ML",
        technology: "Python",
        name: "Aleatory Melody",
        description: "Melody creator based on a musical scale",
        link: "none",
        github: "https://github.com/jsvaldezv/aleatory-melody",
    },
    {
        image: "/py-ml/viewBuilder.png",
        category: "Python and ML",
        technology: "Python and Clingo",
        name: "Smart Builder",
        description: "Drum machine",
        link: "none",
        github: "https://github.com/jsvaldezv/smart-builder",
    },
    {
        image: "/py-ml/viewMixer.png",
        category: "Python and ML",
        technology: "Python and Clingo",
        name: "Smart Mixer",
        description: "Melody creator based on a musical scale",
        link: "none",
        github: "https://github.com/jsvaldezv/smart-mixer",
    },
    // Music Production
    {
        image: "/songs/tramontana.png",
        category: "Music Production",
        technology: "Ableton Live and Pro Tools",
        name: "Soul Cubo - Tramontana",
        description: "Production and mixing",
        link: "https://open.spotify.com/track/5bHwdYhNEWpLear0JwMq2Y?si=0e2e1b9e2bb7484d",
        github: "none",
    },
    {
        image: "/songs/curse.png",
        category: "Music Production",
        technology: "Ableton Live and Pro Tools",
        name: "Serotonina Sintética - Curse",
        description: "Recording and mixing",
        link: "https://open.spotify.com/track/6fFCG4whoCr8jIhOs992Fa?si=3b2f492d0c284201",
        github: "none",
    },
    {
        image: "/songs/huxiono.png",
        category: "Music Production",
        technology: "Ableton Live and Pro Tools",
        name: "Soul Cubo - Huxiono",
        description: "Production and mixing",
        link: "https://open.spotify.com/album/6d9tC8wDosPXl0fPP4wlyA?si=D1VEwt_xR6y8gXET5SUeyQ",
        github: "none",
    },
    {
        image: "/songs/kosako.png",
        category: "Music Production",
        technology: "Ableton Live and Pro Tools",
        name: "Soul Cubo - Kosako",
        description: "Production and mixing",
        link: "https://open.spotify.com/track/6TiQY2CtcBGpaeHGyjtNBR?si=023e23dcbe74423f",
        github: "none",
    },
    {
        image: "/songs/login.png",
        category: "Music Production",
        technology: "Ableton Live",
        name: "AntiCode - Login EP",
        description: "Production, mixing and mastering",
        link: "https://open.spotify.com/album/6nojGFr0Tlcs7n9EXpiHED?si=tZHG1YTVThGVR9-GR9IMIA",
        github: "none",
    },
    {
        image: "/songs/unbreakable.png",
        category: "Music Production",
        technology: "Ableton Live and Pro Tools",
        name: "Brando Hernal - Unbreakable",
        description: "Recording and mixing",
        link: "https://open.spotify.com/album/0L4fwtLkpo24YCUQDDj598?si=NllzrnMUS3KTjTykfqU05Q",
        github: "none",
    },
];