export const projects = [
    // Plugins
    {
        slug: "sweetpoint",
        main_title: "SweetPoint",
        category: "Audio Plug-in",
        short_description: "Smart Stereo Field Optimizer",
        large_description:
            "SweetPoint is an innovative audio plugin designed to smartly optimize your stereo field with transparent mid-side processing. Featuring a unique, in-house-developed smart assistant, SweetPoint provides expert guidance to help you achieve your ideal stereo image effortlessly.",
        external_link: "https://earcandytech.com/sweetpoint",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/sweetpoint.png",
        yt_link:
            "https://www.youtube.com/embed/8JyBXTnEblc?si=Dt496cZ-f84R882P",
        path: "/software/audio-plugin/sweetpoint",
        github: "none",
        padding: true,
        gradient: "linear-gradient(135deg, #d8ce76, #a76989)",
        image_fit: "contain",
    },
    {
        slug: "twizzlay",
        main_title: "Twizzlay",
        category: "Audio Plug-in",
        short_description: "Ping Pong Delay",
        large_description:
            "Twizzlay takes ping-pong delay to the next level. Beyond adding spatial depth and movement, it spices up your sound with exclusive Flavor tuning and streamlines your workflow with Routing. Elevate your sound effortlessly with Twizzlay!",
        external_link: "https://earcandytech.com/twizzlay",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/twizzlay.png",
        yt_link:
            "https://www.youtube.com/embed/t8R5U_CMPIo?si=WsXmGYKAnR1sh1gG",
        path: "/software/audio-plugin/twizzlay",
        github: "none",
        padding: true,
        gradient: "linear-gradient(135deg, #f1c626, #eb5307)",
    },
    {
        slug: "gummy-groove",
        main_title: "Gummy Groove",
        category: "Audio Plug-in",
        short_description: "Vibrant Chorus",
        large_description:
            "Gummy Groove is your ultimate Chorus plugin, designed to enrich your vocals, add depth to instruments and enhance the stereo image of your mix, it boosts your audio with exclusive Flavor tuning and simplifies your creative process with Routing. Gummy Groove is the go-to solution for creating captivating sonic environments.",
        external_link: "https://www.earcandytech.com/gummygroove",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/gummygroove.png",
        yt_link:
            "https://www.youtube.com/embed/t8R5U_CMPIo?si=WsXmGYKAnR1sh1gG",
        path: "/software/audio-plugin/gummy-groove",
        github: "none",
        padding: true,
        gradient: "linear-gradient(135deg, #a7e96a, #3949ea)",
    },
    {
        slug: "phonograin",
        main_title: "Phonograin",
        category: "Audio Plug-in",
        short_description: "Granular Multi FX",
        large_description:
            "Transform any sound into atmospheric pads, glitch fragments, or immersive soundscapes with Phonograin's powerful granular engine and expressive modulation modules. The Granular module is the core of Phonograin. Experiment with up to 5 high-quality granular algorithms. Play with size, pitch, rate and offset to chop and blend all at once.",
        external_link: "https://earcandytech.com/phonograin",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/phonograin.png",
        yt_link:
            "https://www.youtube.com/embed/V8IZB2xz8MA?si=ezoNY268sMlp6VWt",
        path: "/software/audio-plugin/phonograin",
        github: "none",
        padding: true,
        gradient: "linear-gradient(135deg, #31d0a7, rgba(104, 163, 166, 1))",
    },
    {
        slug: "shape",
        main_title: "Shape",
        category: "Audio Plug-in",
        short_description: "Spectral Harmoniser Auditory Perceptual Enhancer",
        large_description:
            "Shape offers a unique take on EQ, focusing on psychoacoustics and equal loudness curves. This powerful, user-friendly plugin enables you to fine-tune the perceived loudness and frequency balance of any sound in a way that is natural, ear-friendly, and inspiring.",
        external_link: "https://www.oikla.com/",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/shape.png",
        yt_link:
            "https://www.youtube.com/embed/PLVGIz-hD2Q?si=sp8_yCK6lJ4MMkQF",
        path: "/software/audio-plugin/shape",
        github: "none",
        padding: true,
        gradient: "linear-gradient(135deg, #4b4b4b, hsl(0, 0%, 0%))",
    },
    {
        slug: "tlaloc",
        main_title: "Tlaloc",
        category: "Audio Plug-in",
        short_description: "Granular Sampler",
        large_description:
            "This granular sampler instrument is designed for creative sound design and advanced sample manipulation, featuring a powerful set of tools for real-time audio experimentation. It includes five unique granular synthesis algorithms, pitch shifting, time stretching, polyphonic voice support, and an integrated recording function for capturing and transforming custom samples instantly.",
        external_link: "none",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/tlaloc.png",
        yt_link:
            "https://www.youtube.com/embed/qafHudaDKiE?si=Kq7yJnPE00aOrfjO",
        path: "/software/audio-plugin/tlaloc",
        github: "none",
        padding: true,
        gradient: "linear-gradient(135deg, #e9ae00, hsl(61, 100%, 41%))",
    },
    {
        slug: "esmeraldaii",
        main_title: "Esmeralda II",
        category: "Audio Plug-in",
        short_description: "Hybrid Reverb",
        large_description:
            "Whether crafting wide pop choruses, cinematic pads, or percussive textures that breathe, Esmeralda II transforms ordinary tracks into immersive, professional mixes. Shape anything from tight rooms to lush halls and abstract FX. Choose between multiple Reverb Types and Impulse Responses for total character control.",
        external_link: "https://earcandytech.com/esmeraldaii",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/esmeraldaii.png",
        yt_link:
            "https://www.youtube.com/embed/KxEpmuFIMKs?si=tJ91z3gGoCRugBJO",
        path: "/software/audio-plugin/esmeraldaii",
        github: "none",
        padding: true,
        gradient: "linear-gradient(135deg, #00c075, #006e32)",
    },
    {
        slug: "rubyii",
        main_title: "Ruby II",
        category: "Audio Plug-in",
        short_description: "Step-Sequenced Delay",
        large_description:
            "Take your tracks from ordinary to unforgettable with Ruby II, the modern delay-tremolo powerhouse inspired by the raw energy and allure of the red gemstone. Effortlessly design custom echo patterns. The intuitive 16-step sequencer turns your delay repeats into creative rhythmic phrases or glitchy rolls.",
        external_link: "https://earcandytech.com/rubyii",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/rubyii.png",
        yt_link:
            "https://www.youtube.com/embed/KxEpmuFIMKs?si=tJ91z3gGoCRugBJO",
        path: "/software/audio-plugin/rubyii",
        github: "none",
        padding: true,
        gradient: "linear-gradient(135deg, #fa1800, #890400)",
    },
    {
        slug: "zafiroii",
        main_title: "Zafiro II",
        category: "Audio Plug-in",
        short_description: "Distortion Shaper",
        large_description:
            "From subtle crisp to sonic destruction, Zafiro II gives you full control over how your sound breaks, warms, or shatters. Elevate your creativity with the metallic edge of this electric-blue gem.",
        external_link: "https://earcandytech.com/zafiroii",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/zafiroii.png",
        yt_link:
            "https://www.youtube.com/embed/KxEpmuFIMKs?si=tJ91z3gGoCRugBJO",
        path: "/software/audio-plugin/zafiroii",
        github: "none",
        padding: true,
        gradient: "linear-gradient(135deg, #00c2e4, #02191d)",
    },
    {
        slug: "obsidian",
        main_title: "Obsidian",
        category: "Audio Plug-in",
        short_description: "Modulated Filter",
        large_description:
            "Unleash a dynamic spectral-shaping effect inspired by the mysterious depth and shifting reflections of the volcanic gemstone. With Obsidian’s wide range of filter types, you can craft everything from gentle tonal shaping to dramatic, shifting textures. Combined with modulation, the filters become highly expressive tools.",
        external_link: "https://earcandytech.com/obsidian",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/obsidian.png",
        yt_link:
            "https://www.youtube.com/embed/KxEpmuFIMKs?si=tJ91z3gGoCRugBJO",
        path: "/software/audio-plugin/obsidian",
        github: "none",
        padding: true,
        gradient: "linear-gradient(135deg, #7a44c6, #26212e)",
    },
    {
        slug: "ambar",
        main_title: "Ambar",
        category: "Audio Plug-in",
        short_description: "Pitch Shifter",
        large_description:
            "From classic musical transpositions to robotic transformations and futuristic spectral textures, Ambar turns any sound into something entirely new. Choose between Classic, Modern, and Spectral to redefine how your sound re-builds. Each mode offers its own personality — musical and warm, synthetic and robotic, or harmonically rich and re-synthesized.",
        external_link: "https://earcandytech.com/ambar",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/ambar.png",
        yt_link:
            "https://www.youtube.com/embed/KxEpmuFIMKs?si=tJ91z3gGoCRugBJO",
        path: "/software/audio-plugin/ambar",
        github: "none",
        padding: true,
        gradient:
            "linear-gradient(135deg, rgb(249, 218, 73), rgb(166, 117, 45))",
    },
    {
        slug: "cicue-spectral",
        main_title: "CiCue Processing Suite",
        category: "Audio Plug-in",
        short_description: "Denoise, EQ, Delay and Pitch Shifting",
        large_description:
            "Audio plugins developed using JUCE and C++, combined with Vite and React.js for building modern, responsive, and interactive user interfaces. These plugins feature advanced audio processing tools including denoise algorithms for noise reduction and signal cleanup, equalization (EQ) for precise tonal shaping, delay effects for spatial depth and rhythmic creativity, and pitch shifting for harmonic transformation and sound design.",
        external_link: "none",
        tech_used: [
            "/logos/JUCE.png",
            "/logos/cpp.png",
            "/logos/vite.png",
            "/logos/react.png",
        ],
        main_image: "/plugins/cicuedecorr.png",
        yt_link: "none",
        path: "/software/audio-plugin/cicue-spectral",
        github: "none",
        padding: true,
        gradient:
            "linear-gradient(135deg, rgb(116, 227, 255), rgb(69, 94, 255))",
        gallery: [
            "/plugins/cicuedecorr.png",
            "/plugins/cicuedenoise.png",
            "/plugins/cicueeq.png",
            "/plugins/pitchdelay.png",
            "/plugins/pitchfdn.png",
            "/plugins/pitchscrambler.png",
        ],
    },
    {
        slug: "spatializer",
        main_title: "Spatializer",
        category: "Audio Plug-in",
        short_description: "Spatialize Audio Through 2,4 and 8 Speakers",
        large_description:
            "A mathematical spatialization tool designed for 4-channel systems, based on equations derived from sine and cosine function analysis. It features two intuitive sliders that control the X and Y position of the sound source, allowing precise placement within the listening space. As the sliders are adjusted, the system dynamically recalculates and distributes the signal across four independent equations—one for each speaker—creating smooth, accurate, and immersive sound movement.",
        external_link: "none",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/spatial.png",
        yt_link: "none",
        path: "/software/audio-plugin/spatializer",
        github: "none",
        padding: true,
        gradient: "linear-gradient(135deg, rgb(94, 69, 255), rgb(0, 18, 81))",
    },
    {
        slug: "funny-distortion",
        main_title: "Funny Distortion",
        category: "Audio Plug-in",
        short_description: "Distortion from subtle warmth to raw power",
        large_description:
            "A versatile distortion plug-in featuring three distinct saturation modes, each designed to deliver unique tonal character and harmonic texture. With fully adjustable Drive, Range, Blend, and Volume controls, it offers precise command over the intensity, frequency response, wet/dry balance, and output level of the effect. Built for creative sound design and mix enhancement, the plug-in can produce everything from subtle analog-style warmth and gentle coloration to heavy saturation, aggressive clipping, and extreme sonic transformation.",
        external_link: "none",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/funnyDistor.png",
        yt_link: "none",
        path: "/software/audio-plugin/funny-distortion",
        github: "none",
        padding: true,
        gradient:
            "linear-gradient(135deg, rgb(0, 122, 12), rgb(102, 102, 102))",
    },
    {
        slug: "banana-split",
        main_title: "Banana Split",
        category: "Audio Plug-in",
        short_description: "FM Synthesizer",
        large_description:
            "An FM-based virtual synthesizer designed for versatile sound creation and expressive performance. It features a powerful single oscillator with selectable waveforms, allowing a wide range of tonal possibilities—from clean digital textures to aggressive synthetic leads and basses. The instrument includes dedicated gain control, a fully adjustable ADSR envelope for precise shaping of dynamics, and an integrated suite of audio effects: Reverb, Delay, Chorus, and Distortion. Together, these tools provide everything needed to craft rich, polished, and production-ready sounds directly within the instrument.",
        external_link: "https://github.com/jsvaldezv/banana-split",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/banana.png",
        yt_link:
            "https://www.youtube.com/embed/Zo8SV2MvIbw?si=WxW14SZExok0zR0F",
        path: "/software/audio-plugin/banana-split",
        github: "https://github.com/jsvaldezv/banana-split",
        padding: true,
        gradient:
            "linear-gradient(135deg, rgb(255, 58, 255), rgba(255, 192, 97, 0.75))",
    },
    {
        slug: "pitch-shifter",
        main_title: "Pitch Shifter",
        category: "Audio Plug-in",
        short_description: "Real-time Pitch Shifting with Total Control",
        large_description:
            "A powerful and intuitive tool for real-time pitch manipulation, designed to give users precise control over the tonal character of any audio signal. Pitch can be shifted by up to ±12 semitones, making it ideal for harmonization, creative sound design, key changes, and tuning correction. Multiple pitch-shifting algorithms are available, allowing users to choose the processing style that best fits their artistic vision or technical requirements. Whether for subtle adjustments or dramatic transformations, it delivers flexible and musical pitch control in real time.",
        external_link:
            "https://github.com/jsvaldezv/pitch-shifter-audio-plugin",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/pitchshifter.png",
        yt_link:
            "https://www.youtube.com/embed/CtgiBxh_xW0?si=jOvRL8Mw_0APSkeX",
        path: "/software/audio-plugin/pitch-shifter",
        github: "https://github.com/jsvaldezv/pitch-shifter-audio-plugin",
        padding: true,
        gradient:
            "linear-gradient(135deg, rgb(0, 16, 157), rgba(0, 2, 129, 0.75))",
    },
    {
        slug: "waveshapers",
        main_title: "Waveshapers",
        category: "Audio Plug-in",
        short_description: "Shape sound with advanced waveshaping distortion",
        large_description:
            "A versatile audio processor designed for exploring a wide range of waveshaping algorithms and sculpting sound through nonlinear distortion. Built for both creative sound design and practical mix processing, it offers multiple shaping modes capable of producing everything from subtle harmonic enhancement to aggressive saturation and extreme tonal transformation. The processor includes comprehensive controls for precise tone shaping: Bypass for instant comparison, selectable waveshaper types, input gain, Drive for distortion intensity, Blend for parallel dry/wet processing, and output gain for final level adjustment. Auto Gain helps maintain consistent loudness during parameter changes, while an integrated limiter protects the output from unwanted clipping. Ideal for producers, engineers, and sound designers seeking flexible distortion with detailed control and professional workflow features.",
        external_link: "none",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/waveshapers.png",
        yt_link:
            "https://www.youtube.com/embed/7sWAE6YXOqU?si=00QuwD3LDlTrCbgZ",
        path: "/software/audio-plugin/waveshapers",
        github: "none",
        padding: true,
        gradient:
            "linear-gradient(135deg, rgb(0, 16, 157), rgba(0, 2, 129, 0.75))",
    },
    {
        slug: "roomline",
        main_title: "Room Line",
        category: "Audio Plug-in",
        short_description: "Hear your mix through any space",
        large_description:
            "A real-time audio processor designed to recreate the tonal characteristics of professional studios, unique rooms, and headphone systems through advanced filter-based processing. Built as a high-performance plug-in, it loads generated filter sets and applies them instantly to incoming audio for accurate monitoring enhancement or creative sound transformation. Using real-time FIR filtering, the processor simulates the frequency response of acoustic spaces and playback systems, allowing users to experience how their mixes translate across different listening environments. Whether emulating control rooms, custom spaces, or headphone correction profiles, it provides a practical solution for better decision-making during production and mixing. Available in standard plug-in formats for seamless integration into modern audio workflows, it bridges acoustic simulation and digital signal processing in an intuitive and efficient tool.",
        external_link: "none",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/roomline.png",
        yt_link: "none",
        path: "/software/audio-plugin/roomline",
        github: "none",
        padding: true,
        gradient:
            "linear-gradient(135deg, rgb(0, 16, 157), rgba(0, 2, 129, 0.75))",
    },
    {
        slug: "schroeder-reverb",
        main_title: "Schroeder Reverb",
        category: "Audio Plug-in",
        short_description: "Explore the science of classic reverb design",
        large_description:
            "An algorithmic reverb project inspired by the classic Schroeder reverb architecture, created to explore the foundations of digital spatial effects through multiple implementation approaches. Designed as both a creative processor and an educational research tool, it examines how different comb and all-pass filter structures shape the character, depth, and realism of reverberation. The project includes four distinct versions of the algorithm, each offering a unique interpretation of the classic design: one using built-in DSP components, custom variants with alternative tuning parameters, and implementations inspired by established reverb design methodologies. These differences allow direct comparison of tonal response, decay behavior, diffusion, and spatial texture. Ideal for sound designers, audio developers, and DSP enthusiasts, the project provides valuable insight into how subtle filter configuration changes can dramatically influence the perception of space and ambience.",
        external_link: "none",
        tech_used: ["/logos/JUCE.png", "/logos/cpp.png"],
        main_image: "/plugins/schroeder-reverb.png",
        yt_link:
            "https://private-user-images.githubusercontent.com/47612276/434162368-7880fcc7-22bb-42ca-bc50-51b9807df8fc.mov?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzc2NzQ4NTgsIm5iZiI6MTc3NzY3NDU1OCwicGF0aCI6Ii80NzYxMjI3Ni80MzQxNjIzNjgtNzg4MGZjYzctMjJiYi00MmNhLWJjNTAtNTFiOTgwN2RmOGZjLm1vdj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNTAxVDIyMjkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMWVkNmQzYzE2OGQwMTdjMjhjMDU2OTcyNWUwMGMxOGNiNWNhOTEyOTc0NWQzMmZlZmFlM2YwMGRiNWMwZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT12aWRlbyUyRnF1aWNrdGltZSJ9.RyrYMtBq-VuNf_c979Mzwcge0tLq-EkofeU63pZYzls",
        path: "/software/audio-plugin/schroeder-reverb",
        github: "none",
        padding: true,
        gradient:
            "linear-gradient(135deg, rgb(0, 16, 157), rgba(0, 2, 129, 0.75))",
    },
    // C++
    {
        slug: "cpp-project-template",
        main_title: "C++ Project Template with CMake",
        category: "C++",
        short_description: "Modern C++ Starts Here",
        large_description:
            "A minimal and clean project template designed to accelerate modern C++ development from day one. It comes preconfigured with CMake, providing a reliable and streamlined build system ready for immediate use. The template includes an organized folder structure and scalable architecture, making it ideal for everything from small experiments to larger applications, tools, or reusable libraries. Built for clarity, efficiency, and growth, it offers a solid foundation for professional C++ projects.",
        external_link:
            "https://github.com/jsvaldezv/cpp-cmake-project-template",
        tech_used: ["/logos/cpp.png", "/logos/cmake.png"],
        main_image: "/logos/cmake.png",
        yt_link: "none",
        path: "/software/cpp/cpp-project-template",
        github: "https://github.com/jsvaldezv/cpp-cmake-project-template",
        padding: true,
        gradient:
            "linear-gradient(135deg, rgb(255, 255, 255), rgba(255, 255, 255, 0.75))",
    },
    {
        slug: "tetris",
        main_title: "Tetris",
        category: "C++",
        short_description: "Classic Tetris, Rebuilt with Precision",
        large_description:
            "A custom recreation of the iconic Tetris puzzle game, built to deliver the timeless gameplay experience with clean performance and responsive controls. Featuring smooth graphics rendering and efficient input handling, the project combines classic mechanics with a modern development structure. Organized with a portable and scalable build system, it serves as both an enjoyable game implementation and a solid example of structured game development practices.",
        external_link: "https://github.com/jsvaldezv/tetris",
        tech_used: ["/logos/cpp.png", "/logos/raylib.png"],
        main_image: "/cpp/tetris.png",
        yt_link:
            "https://private-user-images.githubusercontent.com/47612276/393438783-66d78994-20d0-4c67-9a72-868b454460f6.mp4?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzc2NzI3MDUsIm5iZiI6MTc3NzY3MjQwNSwicGF0aCI6Ii80NzYxMjI3Ni8zOTM0Mzg3ODMtNjZkNzg5OTQtMjBkMC00YzY3LTlhNzItODY4YjQ1NDQ2MGY2Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNTAxVDIxNTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NmMxY2U3MzhiZWM3ZjQzYWMxZDE4OWJjZGRhM2QxNjNhNjg1Y2E0MzI4MzgzZGUwZDdhNjMyMGFlMTVlZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT12aWRlbyUyRm1wNCJ9.1Ss03U2dusev3bRXMCLCn0_5FXQIe3wxbBaH5v-3EHg",
        path: "/software/cpp/tetris",
        github: "https://github.com/jsvaldezv/tetris",
        padding: true,
        gradient: "linear-gradient(135deg, rgb(126, 73, 249), rgb(35, 35, 35))",
    },
    {
        slug: "pong-game",
        main_title: "Pong Game",
        category: "C++",
        short_description: "Classic Pong, reimagined in C++",
        large_description:
            "A minimalist yet fully functional recreation of the classic Pong arcade game, built to capture the fast-paced simplicity that made the original a timeless favorite. It features responsive real-time controls, smooth graphics rendering, and clean gameplay mechanics for an engaging retro experience. Structured with a portable and efficient build system, the project is both a polished game implementation and a strong foundation for learning modern game development practices.",
        external_link: "https://github.com/jsvaldezv/pong-game",
        tech_used: ["/logos/cpp.png", "/logos/raylib.png"],
        main_image: "/cpp/pong.png",
        yt_link:
            "https://www.youtube.com/embed/FG5PA4xKSSo?si=D-ag1ub0aVC-ENc4",
        path: "/software/cpp/pong-game",
        github: "https://github.com/jsvaldezv/pong-game",
        padding: true,
        gradient:
            "linear-gradient(135deg, rgb(73, 249, 228), rgb(0, 141, 101))",
    },
    {
        slug: "space-invaders",
        main_title: "Space Invaders",
        category: "C++",
        short_description: "Classic invasion, rebuilt for today",
        large_description:
            "A modern take on the legendary Space Invaders arcade game, recreated from the ground up to deliver the excitement of classic alien-shooting action with smooth performance and responsive gameplay. Featuring clean visuals, fast controls, and engaging wave-based mechanics, the project captures the spirit of the original while using a structured and scalable development approach. Built with a portable build system, it is both a polished retro-inspired game and a strong example of modern game programming practices.",
        tech_used: ["/logos/cpp.png", "/logos/raylib.png"],
        main_image: "/cpp/space-invaders.png",
        yt_link:
            "https://private-user-images.githubusercontent.com/47612276/393440675-e1f8f65e-2659-44a8-a922-8faf94de8aed.mp4?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzc2NzI3NTYsIm5iZiI6MTc3NzY3MjQ1NiwicGF0aCI6Ii80NzYxMjI3Ni8zOTM0NDA2NzUtZTFmOGY2NWUtMjY1OS00NGE4LWE5MjItOGZhZjk0ZGU4YWVkLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNTAxVDIxNTQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ODQ4OTcwMDQ1Yjc4ZmMyNDYwY2EwYjk1ZmJmYTNhNTljZjYwMjgyZWEzODFmMGE0ZDg2MmFhM2ViOTc4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT12aWRlbyUyRm1wNCJ9.KKXn1jFm9K09uVdDdS-fWVL-L5sHAWNOi4x-SuQpA5E",
        path: "/software/cpp/space-invaders",
        github: "https://github.com/jsvaldezv/space-invaders",
        padding: true,
        gradient: "linear-gradient(135deg, rgb(255, 230, 41), rgb(50, 50, 50))",
    },
    // Web development
    {
        slug: "ect-web",
        main_title: "Ear Candy Technologies Website",
        category: "Web Development",
        short_description: "Modern website brand",
        large_description:
            "The official website of Ear Candy Technologies, designed as a modern digital platform to showcase the company’s products, vision, and innovation in audio technology. Built with a fast and responsive interface, it delivers a seamless user experience across desktop and mobile devices. Featuring a clean visual design, scalable architecture, and cloud-powered functionality, the site serves as a central hub for exploring products, company updates, and brand identity with performance and reliability at its core.",
        external_link: "https://earcandytech.com/",
        tech_used: [
            "/logos/js.png",
            "/logos/react.png",
            "/logos/firebase.png",
            "/logos/tailwind.png",
        ],
        main_image: "/webdev/viewECT.png",
        yt_link: "none",
        path: "/software/web-dev/ect-web",
        github: "none",
        padding: true,
        image_fit: "cover",
        gallery: [
            "/webdev/viewECT1.png",
            "/webdev/viewECT2.png",
            "/webdev/viewECT3.png",
            "/webdev/viewECT4.png",
            "/webdev/viewECT5.png",
            "/webdev/viewECT6.png",
        ],
    },
    {
        slug: "drum-machine",
        main_title: "Real-Time Drum Machine",
        category: "Web Development",
        short_description: "Create beats instantly in your browser",
        large_description:
            "A real-time, browser-based drum machine designed for instant beat creation and rhythmic experimentation. Built entirely with vanilla JavaScript—without frameworks or external libraries—it showcases clean, efficient web development with direct performance-focused execution. Featuring a responsive and intuitive interface, users can trigger sounds, build custom patterns, and shape grooves directly from their browser. Fast, accessible, and creative, it delivers a hands-on music production experience anywhere.",
        external_link: "https://jsvaldezv.github.io/drum-machine/",
        tech_used: ["/logos/js.png"],
        main_image: "/webdev/viewDrum.png",
        yt_link:
            "https://www.youtube.com/embed/nKBvksiq6Ds?si=j6dL81pm4wiPBANr",
        path: "/software/web-dev/drum-machine",
        github: "https://github.com/jsvaldezv/drum-machine",
        padding: true,
        image_fit: "cover",
    },
    {
        slug: "visuals-p5",
        main_title: "p5 Visual Explorations",
        category: "Web Development",
        short_description: "Code-driven visuals in constant motion",
        large_description:
            "A creative collection of generative visuals built with p5.js, designed to run seamlessly in the browser. Each sketch explores the relationship between code, art, and motion through dynamic compositions that evolve in real time. From organic simulations and fluid behaviors to geometric patterns and abstract visual experiments, the collection highlights the expressive potential of creative coding and interactive design.",
        external_link: "https://jsvaldezv.github.io/p5-visual-explorations/",
        tech_used: ["/logos/js.png", "/logos/p5.png"],
        main_image: "/webdev/viewVisualsP5.png",
        yt_link:
            "https://www.youtube.com/embed/VgpMJDB4InI?si=K_c0PuU38JJ9EGjD",
        path: "/software/web-dev/visuals-p5",
        github: "https://github.com/jsvaldezv/p5-visual-explorations",
        padding: true,
        image_fit: "cover",
    },
    {
        slug: "liminal-spaces",
        main_title: "Liminal Spaces",
        category: "Web Development",
        short_description: "A haunting space between myth and memory",
        large_description:
            "A virtual environment inspired by liminal spaces and the legend of La Llorona, designed to evoke mystery, nostalgia, and quiet unease. Featuring transitory settings such as empty corridors, abandoned rooms, and surreal architecture, the experience blends atmospheric world-building with cultural folklore. Through isolation, silence, and haunting visual cues, it creates an immersive space suspended between memory, fear, and the unknown.",
        external_link: "https://github.com/jsvaldezv/liminal-spaces",
        tech_used: ["/logos/js.png", "/logos/three.png"],
        main_image: "/webdev/viewLiminal.png",
        yt_link:
            "https://www.youtube.com/embed/L7oxpoSqHJg?si=RKL3Qc6LFYZzEr-d",
        path: "/software/web-dev/liminal-spaces",
        github: "https://github.com/jsvaldezv/liminal-spaces",
        padding: true,
        image_fit: "cover",
    },
    {
        slug: "synth-kids",
        main_title: "Synth Kids",
        category: "Web Development",
        short_description: "Learn music through play and sound",
        large_description:
            "KidSynth is a fun and interactive web-based synthesizer designed to introduce children to the fundamentals of music theory through hands-on sound exploration. Built with vanilla JavaScript and powered by the Web Audio API, it generates and manipulates sound in real time directly within the browser. With a playful and accessible interface, users can experiment with notes, tones, and melodies while learning core musical concepts in an engaging and creative way.",
        external_link: "https://jsvaldezv.github.io/synth-kids/",
        tech_used: ["/logos/js.png"],
        main_image: "/webdev/viewSynthKids.png",
        yt_link:
            "https://www.youtube.com/embed/qJ8x_vPE3FY?si=vRoEKqU-3h6qR6QD",
        path: "/software/web-dev/synth-kids",
        github: "https://github.com/jsvaldezv/synth-kids",
        padding: true,
        image_fit: "cover",
    },
    {
        slug: "matrix-clock",
        main_title: "Matrix Clock",
        category: "Web Development",
        short_description: "Time meets the Matrix",
        large_description:
            "A stylish digital and analog clock built with vanilla JavaScript, HTML, and CSS, inspired by the iconic Matrix aesthetic. The interface combines sleek visuals with real-time functionality, allowing users to switch seamlessly between digital and analog display modes. Customizable color options add a personalized touch, creating a dynamic and futuristic timekeeping experience directly in the browser.",
        tech_used: ["/logos/js.png"],
        main_image: "/webdev/viewMatrix.png",
        yt_link:
            "https://www.youtube.com/embed/V2Mts2ZvCYU?si=lbF2XY-8GRHY-bkt",
        path: "/software/web-dev/matrix-clock",
        github: "https://github.com/jsvaldezv/matrix-clock",
        padding: true,
        image_fit: "cover",
    },
    // Machine learning
    {
        slug: "instruments-classifier",
        main_title: "Instruments Classifier",
        category: "Python and ML",
        short_description: "Machine learning for instrument recognition",
        large_description:
            "An intelligent instrument classifier designed to identify musical instruments from audio samples using machine learning. Developed in Python with Scikit-learn and featuring a desktop interface powered by PyQt5, the system analyzes extracted audio descriptors to recognize the unique characteristics of different instruments with speed and accuracy. By combining signal analysis with predictive modeling, the classifier provides an efficient tool for audio organization, dataset labeling, music research, and educational applications. It serves as a practical example of how machine learning can be applied to real-world audio recognition tasks.",
        external_link: "https://github.com/jsvaldezv/instruments-classifier",
        tech_used: ["/logos/python.png", "/logos/scikit-learn.png"],
        main_image: "/py-ml/viewClass.png",
        yt_link: "none",
        path: "/software/py-ml/instruments-classifier",
        github: "https://github.com/jsvaldezv/instruments-classifier",
        padding: true,
        image_fit: "cover",
    },
    {
        slug: "midi-arpeggiator",
        main_title: "MIDI Arpeggiator",
        category: "Python and ML",
        short_description: "Turn chords into motion",
        large_description:
            "A dynamic MIDI arpeggiator built with Python, inspired by the creative workflow of Ableton Live's classic arpeggiator. It transforms incoming MIDI notes into automatically generated rhythmic and melodic patterns, turning simple chords into evolving sequences with ease. Designed for producers, composers, and performers, it provides an intuitive way to create movement, groove, and harmonic variation in real time. Ideal for electronic music production, live performance, and rapid idea generation, it brings expressive pattern creation to any MIDI setup.",
        external_link: "https://github.com/jsvaldezv/midi-arpeggiator",
        tech_used: ["/logos/python.png"],
        main_image: "/py-ml/viewArp.png",
        yt_link: "none",
        path: "/software/py-ml/midi-arpeggiator",
        github: "https://github.com/jsvaldezv/midi-arpeggiator",
        padding: true,
        image_fit: "cover",
    },
    {
        slug: "random-melody",
        main_title: "Random Melody",
        category: "Python and ML",
        short_description: "Where music meets quantum randomness",
        large_description:
            "An experimental composition tool for aleatory music creation, designed to generate melodies based on a selected musical scale through controlled randomness. Built with Python, it blends algorithmic composition techniques with modern technology to produce unique melodic ideas and unpredictable musical outcomes. The project also features an innovative implementation using a quantum computer through IonQ on Amazon Braket, leveraging true randomness to inspire new forms of musical creativity. By combining music theory, generative systems, and quantum computing, it offers a forward-thinking approach to composition and sound exploration.",
        external_link: "https://github.com/jsvaldezv/quantum-random-composer",
        tech_used: ["/logos/python.png"],
        main_image: "/py-ml/amazonBraket.png",
        yt_link: "none",
        path: "/software/py-ml/random-melody",
        github: "https://github.com/jsvaldezv/quantum-random-composer",
        padding: true,
        image_fit: "cover",
    },
    {
        slug: "clingo-drum-machine",
        main_title: "Clingo Drum Machine",
        category: "Python and ML",
        short_description: "Smart rhythm generation through logic",
        large_description:
            "An interactive drum machine that combines music production with computational intelligence to generate optimized rhythmic patterns and sound selections. Built with Python and powered by Clingo, it allows users to assign custom sounds for kick, snare, and hi-hat while maintaining a hands-on creative workflow. Using Answer Set Programming (ASP), the system analyzes possible combinations of drum sounds and rhythmic structures to determine the most effective arrangement based on defined logic and constraints. The result is a unique fusion of algorithmic reasoning, sound design, and beat creation.",
        external_link: "https://github.com/jsvaldezv/clingo-drum-machine",
        tech_used: ["/logos/python.png", "/logos/clingo.png"],
        main_image: "/py-ml/viewBuilder.png",
        yt_link:
            "https://www.youtube.com/embed/Qpgreskee0o?si=U9ljWvZNrGQFiFL2",
        path: "/software/py-ml/clingo-drum-machine",
        github: "https://github.com/jsvaldezv/clingo-drum-machine",
        padding: true,
        image_fit: "cover",
    },
    {
        slug: "clingo-mixer",
        main_title: "Clingo Mixer",
        category: "Python and ML",
        short_description: "Automated mixing powered by logic",
        large_description:
            "An intelligent interactive mixer designed to generate multiple audio mixdowns automatically from user-defined instructions. Built with Python and powered by Clingo, it allows users to choose which instruments to include while the system handles mix decisions with speed and consistency. Using logic-based solving, the engine creates optimized mix variations by automatically adjusting volume, stereo panning, and reverb settings for each track. This enables rapid exploration of different sonic balances and creative directions, making it a powerful tool for production workflows, experimentation, and automated mixing research.",
        external_link: "https://github.com/jsvaldezv/clingo-mixer",
        tech_used: ["/logos/python.png", "/logos/clingo.png"],
        main_image: "/py-ml/viewMixer.png",
        yt_link:
            "https://www.youtube.com/embed/hYVwZCYkBZs?si=UtINBKzq8cwBU3vQ",
        path: "/software/py-ml/clingo-mixer",
        github: "https://github.com/jsvaldezv/clingo-mixer",
        padding: true,
        image_fit: "cover",
    },
];
