export const projectData = [
    // Plugins
    {
        image: "/plugins/viewSweetpoint.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "SweetPoint",
        description: "Smart Stereo Field Optimizer",
        link: "/software/audio-plugin/sweetpoint",
        //link: "https://earcandytech.com/sweetpoint",
        github: "none",
        padding: true,
    },
    {
        image: "/plugins/viewTwizzlay.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Twizzlay",
        description: "Ping Pong Delay Audio Plug-in",
        link: "https://earcandytech.com/twizzlay",
        github: "none",
        padding: true,
    },
    {
        image: "/plugins/viewGummy.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Gummy Groove",
        description: "Chorus Audio Plug-in",
        link: "https://earcandytech.com/gummygroove",
        github: "none",
        padding: true,
    },
    {
        image: "/plugins/viewPhono.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Phonograin",
        description: "Granular Multi FX Audio Plug-in",
        link: "https://earcandytech.com/phonograin",
        github: "none",
        padding: true,
    },
    {
        image: "/plugins/viewShape.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Shape",
        description: "Spectral Harmoniser Auditory Perceptual Enhancer",
        link: "https://www.oikla.com/",
        github: "none",
        padding: false,
    },
    {
        image: "/plugins/viewTlaloc.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Tlaloc",
        description: "Granular Sampler",
        link: "none",
        github: "none",
        padding: true,
    },
    {
        image: "/plugins/viewEsme.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Esmeralda",
        description: "Binaural Convolution Reverb",
        link: "https://earcandytech.com/esmeralda",
        github: "none",
        padding: true,
    },
    {
        image: "/plugins/viewRuby.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Ruby",
        description: "Delay with Pitch Shifting",
        link: "https://earcandytech.com/ruby",
        github: "none",
        padding: true,
    },
    {
        image: "/plugins/viewZafiro.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Zafiro",
        description: "Distortion with LFO modulation",
        link: "https://earcandytech.com/zafiro",
        github: "none",
        padding: true,
    },
    {
        image: "/plugins/viewSpatial.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Spatializer",
        description: "Move audio through 2,4 and 8 speakers",
        link: "none",
        github: "none",
        padding: true,
    },
    {
        image: "/plugins/viewFunnyDistor.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Funny Distortion",
        description: "Distortion",
        link: "none",
        github: "none",
        padding: true,
    },
    {
        image: "/plugins/viewBanana.png",
        category: "Audio Plug-in",
        technology: "C++ and JUCE",
        name: "Banana Split",
        description: "FM Synthesiser",
        link: "https://github.com/jsvaldezv/banana-split/releases",
        github: "https://github.com/jsvaldezv/banana-split",
        padding: true,
    },
    // C++
    {
        image: "/cpp/tetris.png",
        category: "C++",
        technology: "C++",
        name: "Tetris",
        description: "Recreation of tetris game",
        link: "none",
        github: "https://github.com/jsvaldezv/tetris",
        padding: true,
    },
    {
        image: "/cpp/pong.png",
        category: "C++",
        technology: "C++",
        name: "Pong Game",
        description: "Recreation of pong game",
        link: "none",
        github: "https://github.com/jsvaldezv/pong-game",
        padding: true,
    },
    {
        image: "/cpp/space-invaders.png",
        category: "C++",
        technology: "C++",
        name: "Space Invaders",
        description: "Recreation of space invaders game",
        link: "none",
        github: "https://github.com/jsvaldezv/space-invaders",
        padding: true,
    },
    // Web development
    {
        image: "/webdev/viewECT.png",
        category: "Web Development",
        technology: "React JS and Firebase",
        name: "Ear Candy Technologies Website",
        description: "Current Company Website",
        link: "https://earcandytech.com/",
        github: "none",
        padding: true,
    },
    {
        image: "/webdev/viewDrum.png",
        category: "Web Development",
        technology: "JavaScript",
        name: "Drum Machine",
        description: "Real Time Drum Machine in the Browser",
        link: "https://jsvaldezv.github.io/drum-machine/",
        github: "https://github.com/jsvaldezv/drum-machine",
        padding: true,
    },
    {
        image: "/webdev/viewVisualsP5.png",
        category: "Web Development",
        technology: "JavaScript and p5",
        name: "Visuals p5",
        description: "Collection of audio visuals made in p5",
        link: "https://jsvaldezv.github.io/visuals-p5/",
        github: "https://github.com/jsvaldezv/visuals-p5",
        padding: true,
    },
    {
        image: "/webdev/viewLiminal.png",
        category: "Web Development",
        technology: "React JS and Three js",
        name: "Liminal Spaces",
        description: "Virtual space inspired by La llorona",
        link: "https://jsvaldezv.github.io/liminal-spaces/",
        github: "https://github.com/jsvaldezv/liminal-spaces",
        padding: true,
    },
    {
        image: "/webdev/viewSynthKids.png",
        category: "Web Development",
        technology: "JavaScript and Web Audio API",
        name: "Synth Kids",
        description: "Synth so children can learn music theory",
        link: "https://jsvaldezv.github.io/synth-kids/",
        github: "https://github.com/jsvaldezv/synth-kids",
        padding: true,
    },
    {
        image: "/webdev/viewPluginsStore.png",
        category: "Web Development",
        technology: "React JS",
        name: "Audio Plug-ins Store",
        description: "Plug-in store as a web application",
        link: "none",
        github: "https://github.com/jsvaldezv/audio-plugins-store",
        padding: true,
    },
    {
        image: "/webdev/viewMatrix.png",
        category: "Web Development",
        technology: "JavaScript",
        name: "Matrix Clock",
        description: "Digital and analog clock with matrix style",
        link: "https://jsvaldezv.github.io/matrix-clock/",
        github: "https://github.com/jsvaldezv/matrix-clock",
        padding: true,
    },
    // Machine learning
    {
        image: "/py-ml/viewClass.png",
        category: "Python and ML",
        technology: "Python and Scikit Learn",
        name: "Instruments Classifier",
        description: "Trained with random forest",
        link: "none",
        github: "https://github.com/jsvaldezv/instruments-classifier",
        padding: true,
    },
    {
        image: "/py-ml/viewArp.png",
        category: "Python and ML",
        technology: "Python",
        name: "MIDI Arpeggiator",
        description: "Arpeggiator based on Ableton's Live arp",
        link: "none",
        github: "https://github.com/jsvaldezv/midi-arpeggiator",
        padding: true,
    },
    {
        image: "",
        category: "Python and ML",
        technology: "Python",
        name: "Aleatory Melody",
        description: "Melody creator based on a musical scale",
        link: "none",
        github: "https://github.com/jsvaldezv/aleatory-melody",
        padding: true,
    },
    {
        image: "/py-ml/viewBuilder.png",
        category: "Python and ML",
        technology: "Python and Clingo",
        name: "Smart Builder",
        description: "Drum machine",
        link: "none",
        github: "https://github.com/jsvaldezv/smart-builder",
        padding: true,
    },
    {
        image: "/py-ml/viewMixer.png",
        category: "Python and ML",
        technology: "Python and Clingo",
        name: "Smart Mixer",
        description: "Melody creator based on a musical scale",
        link: "none",
        github: "https://github.com/jsvaldezv/smart-mixer",
        padding: true,
    },
];
