export const projectData = [
    // Music Production
    {
        main_image: "/songs/tramontana.png",
        category: "Music Production",
        tech_used: "Ableton Live and Pro Tools",
        main_title: "Soul Cubo - Tramontana",
        short_description: "Production and mixing",
        link: "https://open.spotify.com/track/5bHwdYhNEWpLear0JwMq2Y?si=aba90bcb67da4314",
        padding: true,
    },
    {
        main_image: "/songs/curse.png",
        category: "Music Production",
        tech_used: "Ableton Live and Pro Tools",
        main_title: "Serotonina Sintética - Curse",
        short_description: "Recording and mixing",
        link: "https://open.spotify.com/track/6fFCG4whoCr8jIhOs992Fa?si=3b2f492d0c284201",
        padding: true,
    },
    {
        main_image: "/songs/huxiono.png",
        category: "Music Production",
        tech_used: "Ableton Live and Pro Tools",
        main_title: "Soul Cubo - Huxiono",
        short_description: "Production and mixing",
        link: "https://open.spotify.com/track/5Uafg1y8wwJLppJdwsDvjD?si=8da4f157c63e437d",
        padding: true,
    },
    {
        main_image: "/songs/kosako.png",
        category: "Music Production",
        tech_used: "Ableton Live and Pro Tools",
        main_title: "Soul Cubo - Kosako",
        short_description: "Production and mixing",
        link: "https://open.spotify.com/track/6TiQY2CtcBGpaeHGyjtNBR?si=023e23dcbe74423f",
        padding: true,
    },
    {
        main_image: "/songs/login.png",
        category: "Music Production",
        tech_used: "Ableton Live",
        main_title: "AntiCode - Login EP",
        short_description: "Production, mixing and mastering",
        link: "https://open.spotify.com/track/44B07DVzFVuZFfjYQupX2A?si=05d8bc0daa454495",
        padding: true,
    },
    {
        main_image: "/songs/unbreakable.png",
        category: "Music Production",
        tech_used: "Ableton Live and Pro Tools",
        main_title: "Brando Hernal - Unbreakable",
        short_description: "Recording and mixing",
        link: "https://open.spotify.com/track/79hgvUAyg3xW8znUi6WprG?si=228848400578471d",
        padding: true,
    },
];
