export const projectData = [
    // Music Production
    {
        image: "/songs/tramontana.png",
        category: "Music Production",
        technology: "Ableton Live and Pro Tools",
        name: "Soul Cubo - Tramontana",
        description: "Production and mixing",
        link: "https://open.spotify.com/track/5bHwdYhNEWpLear0JwMq2Y?si=0e2e1b9e2bb7484d",
        github: "none",
        padding: true,
    },
    {
        image: "/songs/curse.png",
        category: "Music Production",
        technology: "Ableton Live and Pro Tools",
        name: "Serotonina Sintética - Curse",
        description: "Recording and mixing",
        link: "https://open.spotify.com/track/6fFCG4whoCr8jIhOs992Fa?si=3b2f492d0c284201",
        github: "none",
        padding: true,
    },
    {
        image: "/songs/huxiono.png",
        category: "Music Production",
        technology: "Ableton Live and Pro Tools",
        name: "Soul Cubo - Huxiono",
        description: "Production and mixing",
        link: "https://open.spotify.com/album/6d9tC8wDosPXl0fPP4wlyA?si=D1VEwt_xR6y8gXET5SUeyQ",
        github: "none",
        padding: true,
    },
    {
        image: "/songs/kosako.png",
        category: "Music Production",
        technology: "Ableton Live and Pro Tools",
        name: "Soul Cubo - Kosako",
        description: "Production and mixing",
        link: "https://open.spotify.com/track/6TiQY2CtcBGpaeHGyjtNBR?si=023e23dcbe74423f",
        github: "none",
        padding: true,
    },
    {
        image: "/songs/login.png",
        category: "Music Production",
        technology: "Ableton Live",
        name: "AntiCode - Login EP",
        description: "Production, mixing and mastering",
        link: "https://open.spotify.com/album/6nojGFr0Tlcs7n9EXpiHED?si=tZHG1YTVThGVR9-GR9IMIA",
        github: "none",
        padding: true,
    },
    {
        image: "/songs/unbreakable.png",
        category: "Music Production",
        technology: "Ableton Live and Pro Tools",
        name: "Brando Hernal - Unbreakable",
        description: "Recording and mixing",
        link: "https://open.spotify.com/album/0L4fwtLkpo24YCUQDDj598?si=NllzrnMUS3KTjTykfqU05Q",
        github: "none",
        padding: true,
    },
];
